name: build-fonbet
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          pip install jinja2
      # здесь может быть шаг парсинга, который обновляет data/fonbet.json
      - name: Build HTML from template
        run: |
          python scripts/build.py
      - name: Commit site
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add promo-fonbet.html data/fonbet.json
          git commit -m "build: update promo-fonbet" || echo "No changes"
          git push

