name: Build promo pages

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'templates/**'
      - 'assets/**'
      - '.github/workflows/build-pages.yml'
  workflow_dispatch:

permissions:
  contents: write   # нужна запись, чтобы закоммитить сгенерированные HTML

concurrency:
  group: build-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Render pages from templates
        run: |
          python - <<'PY'
          import json, pathlib
          from jinja2 import Environment, FileSystemLoader, select_autoescape

          root = pathlib.Path('.').resolve()
          env = Environment(
              loader=FileSystemLoader(str(root / 'templates')),
              autoescape=select_autoescape(['html', 'xml'])
          )

          def render(data_file, template_file, out_file):
              data = json.loads((root / 'data' / data_file).read_text(encoding='utf-8'))
              html = env.get_template(template_file).render(data=data)
              (root / out_file).write_text(html, encoding='utf-8')
              print(f'✔ Rendered {out_file}')

          # Собираем обе страницы
          render('fonbet.json',   'promo-fonbet.html.j2',   'promo-fonbet.html')
          render('winline.json',  'promo-winline.html.j2',  'promo-winline.html')
          PY

      - name: Commit rendered HTML
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add promo-fonbet.html promo-winline.html
          git commit -m "chore(build): render promo pages" || echo "No changes to commit"
          git push

      # Если у тебя включён GitHub Pages через workflow pages-build-deployment,
      # этот шаг не обязателен. Оставляем как коммент на случай ручного деплоя.
      # - name: Trigger Pages build (optional)
      #   run: echo "Rendered pages committed; Pages will deploy via existing workflow."
