name: run-test
on:
  workflow_dispatch: {}   # запуск вручную
  schedule:
    - cron: "0 7 * * *"   # каждый день в 07:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run script
        run: python scripts/test.py
